apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: ledger-api
  namespace: argocd

spec:
  project: ledger-api

  source:
    repoURL: https://github.com/Nishant-S-Bhardaj/ledger-api-assignment
    targetRevision: main
    path: k8s/base

  destination:
    server: https://kubernetes.default.svc
    namespace: payments

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true