---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ledger-api-secrets
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgA172+M1LWxroLbEQgkKxM4AKSxTHnuHZIvSWspoNtqp1F+smo2Sk1aypcin7NMohGDyVCRt7E8Yi3MBY4XRn7jzUB6Sh37NmKM4DHW7Kz7w4k3VmfTpkGuo4BHTJIsKxVmKfS9LaimG3dOtx/3MDFfK1Ax+U0EngXoL+mvN8mINgd65vIH6cZyhyazZ6Gk49fp9K8jaKHh8YhO3zvnTazCGil0mSDtEDjo2EOplUAYnDgM78zbvTFvB0B1IvRPNi/1IGIQ0qsKPnXSoSy5YBjtz9qeX6NZ0XCK/ah+WmidpnSve30r7hXJRSt0kXI7+tDILVwGVhjaKj4JvU3bnaMwGp1x8focuyESjQ0r9Xk2ObumGowsow/Jlochp9swx/4JI2b8EXOatshJNyTc3Qt85hgm/FOOTcnphd/MM+aalusOCLV6FBzeB9ZCK0HnTMFxMUpupyzc+VKBqzWQ+pBpzQQcm5O4PpIapXvsVavHVyQXQeAt47//PyEbPb1st1z8kWOnQ5kmgqOV6gLbc2mtbd074BRpPHzEWjm8HJkeMXfgor1BpV4stUSTaQbnvcJCy5KXH1yeiEPn80pjw0dkIIysFedBjXaER5dca4FMkesqz8n4HzSLILSNFsEspvSNh+eNfiz5lRacNVXlCc5EHF1xN2dFxQCgNtcZOz3FKPqkLOfbIA8Xdm1B+GtKBGIBk0M1dQIY9EBzQNn8
    STRIPE_API_KEY: AgAl3rP2o0ntYrH+0TRX4M6B4jaLJuhqyBz8kJal2S5qi3D+nszR9bPo0SSBZgeuhYVmiqikbW8e4vnAEhenI4+ByP7/ry0tiW2IpZbWvQJEb9fmPUMtLjnWk8NyR3IJapV9Z0aTtge29NNGGeBYJOAGcJGiDCXLfMKXrWXK4JckAVdFV6MdSUDy3MSLxZZx76XdiUG03vsz39U50DqBCllJoNj6zACB6OAy1UZRFHIcg2ViLV5054qmksUwuW5x6zFvUis2l5Pp8UAtCBXGBfZolNcOWQMwbb/UtgMJKYLqwru1X9vvJVos+McvEsl3HvpnzuW1XoVAOFeccNdGMCVy/pInFkCIFbIxl4ug3CYPx3JK/H6HsyLPFkV0k40zMeEGUTaF2p+abtFjB7siU1fgcrir/EeNTNl672AaEaPGgDbwKPDVicRjHlgD2PZVhyWLo/o5snToRI2qE7lVGp57/3FPC+pRBKLCJEHHliHwj9QdavecYKCIkWHHt0xVzGl/HuEBftlOE9alZ8kbHH59p+JINznvd05x+UBEMxQmf7JdfT3dQhV9DgDlJwRZyaRqZrYd962MIjvVNFUX+oxdbsg7Rvs6Z05QDECOsavd0xsik4ay2gq4NUBA6t/DXuC8NE79KkPhvP6r8KrVdDoBgIos/wWyv2NTVZuWc+1mH3AjEt+KvywM5Eum+PBsJMNQQwbB1uH4cos8UXeIIyMT
  template:
    metadata:
      creationTimestamp: null
      name: ledger-api-secrets
      namespace: payments
    type: Opaque
